version: '3.8'
services:
  openfids:
    build: 
      context: ./php-apache
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:80"
    networks:
        - ctf-6.external
        - ctf-6.internal
    hostname: openfids
    container_name: openfids
    restart: always

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword 
      MYSQL_DATABASE: fids
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      networks:
          - ctf-6.internal
      container_name: db
      hostname: db
      


  #phpmyadmin:
    #image: phpmyadmin/phpmyadmin
    #restart: always
    #depends_on:
     # - db
    #environment:
      #PMA_HOST: db
      #PMA_USER: openfids
      #PMA_PASSWORD: Lt69lzYJNoLCPH5s
    #ports:
      #- "8081:80"
  kali:
    build:
      context: ./kali
      dockerfile: Dockerfile
    restart: always
    networks:
        - ctf-6.external
    hostname: kali
    container_name: kali 

volumes:
  db_data:

networks:
    ctf-6.external:
        driver: bridge
        ipam:
            driver: default
    ctf-6.internal:
        driver: bridge
        ipam:
            driver: default
        internal: true