version: '3.8'
services:
  openfids:
    build: 
      context: ./php-apache
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:80"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword 
      MYSQL_DATABASE: fids
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      #PMA_USER: openfids
      #PMA_PASSWORD: Lt69lzYJNoLCPH5s
    ports:
      - "8081:80"
  kali:
    build:
      context: ./kali
      dockerfile: Dockerfile
    ports:
      - "9090:80"

volumes:
  db_data:
