version: '3.8'
services:
  openfids:
    build: 
      context: ./php-apache
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:80"
    hostname: openfids
    container_name: openfids
    restart: always

  db:
    build: 
      context: ./mysql
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword 
      MYSQL_DATABASE: fids
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      container_name: db
      hostname: db
  #phpmyadmin:
    #image: phpmyadmin/phpmyadmin
    #restart: always
    #depends_on:
     # - db
    #environment:
      #PMA_HOST: db
      #PMA_USER: openfids
      #PMA_PASSWORD: Lt69lzYJNoLCPH5s
    #ports:
      #- "8081:80"
  kali:
    build:
      context: ./kali
      dockerfile: Dockerfile
    restart: always
    hostname: kali
    container_name: kali 
    cap_add:
      - NET_ADMIN
      - NET_RAW
    privileged: true

volumes:
  db_data:

