FROM kalilinux/kali-rolling:latest

RUN apt update -y && apt install -y openssh-client nmap net-tools dirb gobuster netcat-traditional
# RUN apt update -y && apt install -y openssh-client nmap iproute2 net-tools iputils-ping dirb gobuster netcat-traditional

# Start a Bash shell and tail to keep the container running
# When the container starts, automatically drop into a shell
CMD ["/bin/bash"]
CMD ["tail", "-f", "/dev/null"]